function [ data ] = z1_SYNTH_DATA_h_kappa(par,trudata,trumodel,ifplot)
%% brb2022.02.08 Function to calculate synthetic h-kappa stack from
% synthetic receiver functions. 

ifplot = false; warning('brb2022.02.08 remove ifplot')

samprate = par.synth.samprate;
data = trudata; 

for id = 1:length(par.inv.datatypes)
    pdtyps(id,:) = parse_dtype(par.inv.datatypes{id}); 
end

%% ==================== Get H-kappa stack using P wave receiver function ==
if any(string(pdtyps(:,1))=='HKstack'); % Use the Ps receiver function to get h-kappa stack

    %%% This wrapper takes the receiver function waveforms we have
    % and makes HK stack while accounting for radial anisotropy. 
    waves = struct('rf',   trudata.RF_Ps.PSV(:,2), ...
                   'tt',   trudata.RF_Ps.tt, ...
                   'rayParmSecDeg', trudata.RF_Ps.rayp); % Parameters used in forward modelling HK stack on waveforms. 
    
               
    trumodelIso = trumodel;
    trumodelIso.Panis = trumodel.Panis .* 0; 
    trumodelIso.Sanis = trumodel.Sanis .* 0; 
    [HK_A_noan, HK_H_noan, HK_K_noan, t_pred_noan] = HKstack_anis_wrapper(par, trumodelIso, ...
        waves.rf, waves.tt, waves.rayParmSecDeg,...
        'ifplot', ifplot, ...
        'hBounds', [par.mod.crust.hmin, par.mod.crust.hmax], ...
        'kBounds', [par.mod.crust.vpvsmin, par.mod.crust.vpvsmax], ...
        'hNum', par.datprocess.hNum, 'kNum', par.datprocess.kNum); 
    
% 
    [HK_A, HK_H, HK_K, t_pred] = HKstack_anis_wrapper(par, trumodel, ...
        waves.rf, waves.tt, waves.rayParmSecDeg,...
        'ifplot', ifplot, ...
        'hBounds', [par.mod.crust.hmin, par.mod.crust.hmax], ...
        'kBounds', [par.mod.crust.vpvsmin, par.mod.crust.vpvsmax], ...
        'hNum', par.datprocess.hNum, 'kNum', par.datprocess.kNum); 
    
    if ifplot 
        plot_HK_stack(HK_H, HK_K, HK_A, ...
            'model_vpvs', trumodel.vpvs, 'model_zmoh', trumodel.zmoh, ...
            'title', sprintf('Synthetic H-kappa stack (true model values)'),...
            'figNum', 198 ,...
            'saveString', sprintf('%s/HK_stack_synth_truparms.pdf',par.res.resdir) ); 
    end

    % Store stack info in structure. 
    HKstack_P = struct('H', HK_H, 'K', HK_K', 'Esum', HK_A, ...
        'Nobs', par.mod.data.deg_of_freedom.h_kappa, ...
        'dof' , par.mod.data.deg_of_freedom.h_kappa, ...
        'waves', waves, 'RF_Ps', data.RF_Ps, 't_pred', t_pred); 

    HKstack_P_noan = struct('H', HK_H_noan, 'K', HK_K_noan', 'Esum', HK_A_noan, ...
        'Nobs', par.mod.data.deg_of_freedom.h_kappa, ...
        'dof' , par.mod.data.deg_of_freedom.h_kappa, ...
        'waves', waves, 'RF_Ps', data.RF_Ps, 't_pred', t_pred_noan); 
    
    HKstack_P.E_by_Esuper_max = ...
        hk_maximum_possible_value(waves.rf, waves.tt); 
    
    data.HKstack_P = HKstack_P; 
    data.HKstack_P_noan = HKstack_P_noan; 
        
    % We needed to calculate synthetic receiver function just to get h-kappa stack. Now, remove the receiver function time series from data. 
    disp('Removing RF_Ps from data, keeping only h-kappa stack.')
    data = rmfield(data, 'RF_Ps'); 
end



end