% % function [Emax] = hk_max_optimize(RF
% % 
% % 
% % HK_new = zeros(size(predata.HKstack_P.Esum)); 
% % for iWave = [1:size(predata.HKstack_P.waves.rf,2)]; 
% % %     RF   = predata.HKstack_P.waves.rf(:,iWave); 
% %     tt   = predata.HKstack_P.waves.tt; 
% %     rayp = predata.HKstack_P.waves.rayParmSecDeg(iWave); 
% %     [HK_A, HK_H, HK_K] = HKstack_anis_wrapper(...
% %         par, model, RF, tt, rayp, 'ifplot', false, ...
% %         'hBounds', [par.mod.crust.hmin, par.mod.crust.hmax], ...
% %         'kBounds', [par.mod.crust.vpvsmin, par.mod.crust.vpvsmax], ...
% %         'kNum', size(HK_new,1), 'hNum', size(HK_new,2),...
% %         'posterior', options.posterior);   
% %     HK_new = HK_new + HK_A; 
% % end
% % 
% % [HK_A, HK_H, HK_K] = HKstack(RF, tt, ...
% %     rayp/111.1949, phase_wts, ...
% %     vsAv, ...
% %     linspace(options.hBounds(1), options.hBounds(2), options.hNum)',...
% %     linspace(options.kBounds(1), options.kBounds(2), options.kNum), ...
% %     'vpvsANIS_vpvs',vpvsEffective/model.vpvs,'Vsv_av',vsvAn)
% % 
% % )